name: Deploy to server

on:
  workflow_dispatch:

jobs:
  build_site:
    runs-on: self-hosted
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: Deploy
      run: docker compose up --build -d
    env:
      NODE_ENV: production
      DATABASE_URL: ${{secrets.DATABASE_URL}}
